<?php

/**
 * @file
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\user\UserInterface;

function slv_manager_user_login(UserInterface $account) {
  // We want to redirect user on login.
  // Check if the first login or not.
  if(!$account->hasPermission('administer voter entity')) {
    $entity = getVoter($account->get('field_nic_number')->getValue()[0]);
    $role = $entity->get('role')->getValue()[0]['value'];
    if (!$account->hasRole($role)) {
      $account->addRole($role);
      $account->save();
    }
    if ($account->getLastAccessedTime() == 0) {
      addUser($account->id(), $entity->id());
      $response = new RedirectResponse(Url::fromRoute('slv_manager.voter_welcome')
        ->toString(), 302);
      $response->send();
      return;
    }
    //@todo check the voters and other roles separately
    else {
      if (!empty($entity)) {

        $response = new RedirectResponse(Url::fromRoute('slv_manager.voter_details', array('slv_manager_voter' => $entity->id()))
          ->toString(), 302);
        $response->send();
      }
    }
    return;
  }
}

function getVoter($nic){
  $entities = entity_load_multiple_by_properties('slv_manager_voter', array('nic' => $nic['value']));
  return reset($entities);
}

function addUser($uid, $voter_id){
  /* @var $voter \Drupal\slv_manager\Entity\Voter */
  $voter = entity_load('slv_manager_voter', $voter_id);
  $voter->set('user_id', $uid);
  $voter->save();
}

function slv_manager_form_user_profile_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['simplenews']['subscriptions'] = array(
    '#type' => 'checkboxes',
    '#options' => '',
    '#default_value' => 'aa',
  );
}
